name: "Deploy Gothic Output Inspector"

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: WPFUI/WPFUI.csproj
  CONFIGURATION: -p:Configuration=Release -p:IncludeAllContentForSelfExtract=true -p:SelfContained=true -restore -target:publish

jobs:
  Deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Calculate next version
        uses: cezarypiatek/NextVersionGeneratorAction@0.4
        with:
          major-pattern: 'BREAKING CHANGES:'
          minor-pattern: '.*'
          patch-pattern: '.*'
          output-to-env-variable: 'VersionPrefix'


      - name: Dotnet Build x64
        run: dotnet build ${{ env.CONFIGURATION }} -p:Runtimeidentifier=win-x64 "${{ env.PROJECT_PATH }}"

      - name: Dotnet Build x86
        run: dotnet build ${{ env.CONFIGURATION }} -p:Runtimeidentifier=win-x86 "${{ env.PROJECT_PATH }}"

      - name: Create directory
        run: md completed

      - name: Copy Exe x64
        run: copy WPFUI/bin/Release/net7.0-windows/win-x64/publish/*.exe "completed/Gothic_Output_Inspector_${{ env.VersionPrefix }}_x64.exe"

      - name: Copy Exe x86
        run: copy WPFUI/bin/Release/net7.0-windows/win-x86/publish/*.exe "completed/Gothic_Output_Inspector_${{ env.VersionPrefix }}_x86.exe"


      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload Release
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: completed/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
